Hugo version of Pinniped site
vmware-tanzu/pinniped pull request #188
Opened 2020-11-06 22:44 UTC by A-P

**Release note**:

```release-note

```

2020-11-09 15:26 UTC, jonasrosland requested changes
This looks great, thank you @A-P !

A few changes requested in the review.
I think we can get rid of some images like `site/themes/pinniped/images/splash.png`, tn.png,  and similar.
I believe we have a new image sent over as a replacement for `site/themes/pinniped/static/img/andrew-keesler.png`

2020-11-09 15:26 UTC, jonasrosland commented on site/resources/_gen/assets/scss/scss/site.scss_8967e03afb92eb0cac064520bf021ba2.json
> +{"Target":"css/style.css","MediaType":"text/css","Data":{}}
Are these files needed here, or are they automatically generated during build?

2020-11-09 15:26 UTC, jonasrosland commented on site/content/posts/blog-article-9.md
> +---
Can you please remove these extra blog posts?

2020-11-10 20:51 UTC, mattmoyer approved these changes

2020-11-10 20:51 UTC, merged