webhookcachefiller: be stricter about CA bundle validation
vmware-tanzu/pinniped pull request #588
Opened 2021-04-28 17:53 UTC by enj

Signed-off-by: Monis Khan <mok@vmware.com>

```release-note
NONE
```

2021-04-28 18:00 UTC, mattmoyer requested changes
Overall +1 on the change but I think we should keep the existing behavior for empty strings.

2021-04-29 09:50 UTC, enj commented on internal/controller/authenticator/authenticator.go
> +		return nil, fmt.Errorf("certificateAuthorityData is not valid pem")
Fixed.

2021-04-29 09:51 UTC, enj commented on internal/controller/authenticator/authenticator.go
> +	return pem, nil
Fixed.

2021-04-29 11:25 UTC, mattmoyer approved these changes

2021-04-29 11:47 UTC, merged